-- CreateTable
CREATE TABLE `CHI_TIET_DAT_PHONG` (
    `MaDatPhong` INTEGER NOT NULL,
    `MaHomestay` INTEGER NOT NULL,
    `SoLuongPhong` INTEGER NOT NULL,

    INDEX `MaHomestay`(`MaHomestay`),
    PRIMARY KEY (`MaDatPhong`, `MaHomestay`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CHU_HOMESTAY` (
    `MaChu` INTEGER NOT NULL AUTO_INCREMENT,
    `HoTen` VARCHAR(100) NOT NULL,
    `Email` VARCHAR(100) NOT NULL,
    `MatKhau` VARCHAR(255) NOT NULL,
    `SoDienThoai` VARCHAR(15) NULL,
    `DiaChi` VARCHAR(255) NULL,
    `SoCCCD` VARCHAR(20) NOT NULL,
    `Quyen` ENUM('admin', 'chu_homestay') NULL DEFAULT 'chu_homestay',
    `created_at` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
    `passwordResetToken` VARCHAR(191) NULL,
    `passwordResetExpires` DATETIME(3) NULL,

    UNIQUE INDEX `Email`(`Email`),
    UNIQUE INDEX `SoCCCD`(`SoCCCD`),
    UNIQUE INDEX `CHU_HOMESTAY_passwordResetToken_key`(`passwordResetToken`),
    PRIMARY KEY (`MaChu`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DANH_GIA` (
    `MaDanhGia` INTEGER NOT NULL AUTO_INCREMENT,
    `MaNguoiDung` INTEGER NOT NULL,
    `MaHomestay` INTEGER NOT NULL,
    `SoSao` INTEGER NULL,
    `BinhLuan` TEXT NULL,
    `created_at` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX `MaHomestay`(`MaHomestay`),
    INDEX `MaNguoiDung`(`MaNguoiDung`),
    PRIMARY KEY (`MaDanhGia`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DAT_PHONG` (
    `MaDatPhong` INTEGER NOT NULL AUTO_INCREMENT,
    `MaNguoiDung` INTEGER NOT NULL,
    `NgayNhan` DATE NOT NULL,
    `NgayTra` DATE NOT NULL,
    `SoLuong` INTEGER NOT NULL,
    `Gia` DECIMAL(12, 2) NOT NULL,
    `TrangThai` ENUM('ChoXacNhan', 'DaXacNhan', 'DaHuy') NULL DEFAULT 'ChoXacNhan',
    `created_at` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX `MaNguoiDung`(`MaNguoiDung`),
    PRIMARY KEY (`MaDatPhong`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DOANH_THU` (
    `MaDoanhThu` INTEGER NOT NULL AUTO_INCREMENT,
    `MaChu` INTEGER NOT NULL,
    `ThangNam` VARCHAR(7) NULL,
    `TongDoanhThu` DECIMAL(12, 2) NULL DEFAULT 0.00,
    `SoLuongDat` INTEGER NULL DEFAULT 0,
    `created_at` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX `MaChu`(`MaChu`),
    PRIMARY KEY (`MaDoanhThu`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `HINH_ANH` (
    `MaAnh` INTEGER NOT NULL AUTO_INCREMENT,
    `MaHomestay` INTEGER NOT NULL,
    `HinhAnh` LONGBLOB NULL,

    INDEX `MaHomestay`(`MaHomestay`),
    PRIMARY KEY (`MaAnh`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `HOMESTAY` (
    `MaHomestay` INTEGER NOT NULL AUTO_INCREMENT,
    `MaChu` INTEGER NOT NULL,
    `TenHomestay` VARCHAR(255) NOT NULL,
    `DiaDiem` VARCHAR(255) NOT NULL,
    `Gia` DECIMAL(12, 2) NOT NULL,
    `SoKhachToiDa` INTEGER NOT NULL,
    `TienIch` TEXT NULL,
    `MoTa` TEXT NULL,
    `created_at` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX `MaChu`(`MaChu`),
    PRIMARY KEY (`MaHomestay`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `KHIEU_NAI` (
    `MaKhieuNai` INTEGER NOT NULL AUTO_INCREMENT,
    `MaDatPhong` INTEGER NOT NULL,
    `MaNguoiDung` INTEGER NOT NULL,
    `NoiDung` TEXT NOT NULL,
    `TrangThai` ENUM('ChuaXuLy', 'DangXuLy', 'DaXuLy') NULL DEFAULT 'ChuaXuLy',
    `NgayTao` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX `MaDatPhong`(`MaDatPhong`),
    INDEX `MaNguoiDung`(`MaNguoiDung`),
    PRIMARY KEY (`MaKhieuNai`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `NGUOI_DUNG` (
    `MaNguoiDung` INTEGER NOT NULL AUTO_INCREMENT,
    `HoTen` VARCHAR(100) NOT NULL,
    `Email` VARCHAR(100) NOT NULL,
    `MatKhau` VARCHAR(255) NOT NULL,
    `SoDienThoai` VARCHAR(15) NULL,
    `DiaChi` VARCHAR(255) NULL,
    `CapNhatDL` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
    `passwordResetToken` VARCHAR(191) NULL,
    `passwordResetExpires` DATETIME(3) NULL,

    UNIQUE INDEX `Email`(`Email`),
    UNIQUE INDEX `NGUOI_DUNG_passwordResetToken_key`(`passwordResetToken`),
    PRIMARY KEY (`MaNguoiDung`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PHIEU_KHIEU_NAI` (
    `MaChu` INTEGER NOT NULL,
    `MaKhieuNai` INTEGER NOT NULL,

    INDEX `MaKhieuNai`(`MaKhieuNai`),
    PRIMARY KEY (`MaChu`, `MaKhieuNai`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `XU_LY_KHIEU_NAI` (
    `MaXuLy` INTEGER NOT NULL AUTO_INCREMENT,
    `MaKhieuNai` INTEGER NOT NULL,
    `MaChu` INTEGER NOT NULL,
    `KetQua` TEXT NULL,
    `NgayXuLy` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX `MaChu`(`MaChu`),
    INDEX `MaKhieuNai`(`MaKhieuNai`),
    PRIMARY KEY (`MaXuLy`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `YEU_THICH` (
    `MaNguoiDung` INTEGER NOT NULL,
    `MaHomestay` INTEGER NOT NULL,
    `NgayThem` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX `MaHomestay`(`MaHomestay`),
    PRIMARY KEY (`MaNguoiDung`, `MaHomestay`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `CHI_TIET_DAT_PHONG` ADD CONSTRAINT `CHI_TIET_DAT_PHONG_ibfk_1` FOREIGN KEY (`MaDatPhong`) REFERENCES `DAT_PHONG`(`MaDatPhong`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CHI_TIET_DAT_PHONG` ADD CONSTRAINT `CHI_TIET_DAT_PHONG_ibfk_2` FOREIGN KEY (`MaHomestay`) REFERENCES `HOMESTAY`(`MaHomestay`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DANH_GIA` ADD CONSTRAINT `DANH_GIA_ibfk_1` FOREIGN KEY (`MaNguoiDung`) REFERENCES `NGUOI_DUNG`(`MaNguoiDung`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DANH_GIA` ADD CONSTRAINT `DANH_GIA_ibfk_2` FOREIGN KEY (`MaHomestay`) REFERENCES `HOMESTAY`(`MaHomestay`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DAT_PHONG` ADD CONSTRAINT `DAT_PHONG_ibfk_1` FOREIGN KEY (`MaNguoiDung`) REFERENCES `NGUOI_DUNG`(`MaNguoiDung`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DOANH_THU` ADD CONSTRAINT `DOANH_THU_ibfk_1` FOREIGN KEY (`MaChu`) REFERENCES `CHU_HOMESTAY`(`MaChu`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `HINH_ANH` ADD CONSTRAINT `HINH_ANH_ibfk_1` FOREIGN KEY (`MaHomestay`) REFERENCES `HOMESTAY`(`MaHomestay`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `HOMESTAY` ADD CONSTRAINT `HOMESTAY_ibfk_1` FOREIGN KEY (`MaChu`) REFERENCES `CHU_HOMESTAY`(`MaChu`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `KHIEU_NAI` ADD CONSTRAINT `KHIEU_NAI_ibfk_1` FOREIGN KEY (`MaDatPhong`) REFERENCES `DAT_PHONG`(`MaDatPhong`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `KHIEU_NAI` ADD CONSTRAINT `KHIEU_NAI_ibfk_2` FOREIGN KEY (`MaNguoiDung`) REFERENCES `NGUOI_DUNG`(`MaNguoiDung`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PHIEU_KHIEU_NAI` ADD CONSTRAINT `PHIEU_KHIEU_NAI_ibfk_1` FOREIGN KEY (`MaChu`) REFERENCES `CHU_HOMESTAY`(`MaChu`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PHIEU_KHIEU_NAI` ADD CONSTRAINT `PHIEU_KHIEU_NAI_ibfk_2` FOREIGN KEY (`MaKhieuNai`) REFERENCES `KHIEU_NAI`(`MaKhieuNai`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `XU_LY_KHIEU_NAI` ADD CONSTRAINT `XU_LY_KHIEU_NAI_ibfk_1` FOREIGN KEY (`MaKhieuNai`) REFERENCES `KHIEU_NAI`(`MaKhieuNai`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `XU_LY_KHIEU_NAI` ADD CONSTRAINT `XU_LY_KHIEU_NAI_ibfk_2` FOREIGN KEY (`MaChu`) REFERENCES `CHU_HOMESTAY`(`MaChu`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `YEU_THICH` ADD CONSTRAINT `YEU_THICH_ibfk_1` FOREIGN KEY (`MaNguoiDung`) REFERENCES `NGUOI_DUNG`(`MaNguoiDung`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `YEU_THICH` ADD CONSTRAINT `YEU_THICH_ibfk_2` FOREIGN KEY (`MaHomestay`) REFERENCES `HOMESTAY`(`MaHomestay`) ON DELETE CASCADE ON UPDATE CASCADE;
